# Generated by Django 4.2.24 on 2025-10-11 06:27

import apps.tasks.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', apps.tasks.models.SnowflakePK(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите уникальное название категории', max_length=150, unique=True, verbose_name='Название категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', apps.tasks.models.SnowflakePK(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Введите короткое название задачи', max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, help_text='Можно указать дополнительные детали задачи', verbose_name='Описание задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('done', models.BooleanField(default=False, help_text='Отметьте, если задача завершена', verbose_name='Выполнено')),
                ('created_reminder_sent', models.BooleanField(default=False, verbose_name='Напоминание о создании отправлено')),
                ('due_reminder_sent', models.BooleanField(default=False, verbose_name='Напоминание о дедлайне отправлено')),
                ('categories', models.ManyToManyField(blank=True, related_name='tasks', to='tasks.category', verbose_name='Категории')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.tguser', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
