# Generated by Django 4.2.24 on 2025-10-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок рассылки')),
                ('prompt_text', models.TextField(verbose_name='Текст или промпт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'рассылки',
                'verbose_name_plural': 'рассылки',
                'db_table': 'broadcast_prompt',
                'ordering': ['-created_at'],
            },
        ),
    ]
