# Generated by Django 4.2.24 on 2025-10-07 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Введите имя и фамилию ученика', max_length=100, verbose_name='Имя ученика')),
                ('lesson', models.CharField(choices=[('Введение в Python', 'Введение в Python. Переменные, типы данных'), ('Условные конструкции', 'Условные конструкции (if, else, elif)'), ('Циклы', 'Циклы for, while'), ('Списки', 'Списки, срезы, кортежи'), ('Словари и множества', 'Словари, множества'), ('Функции', 'Функции, *args, **kwargs'), ('Lambda и исключения', 'Lambda, исключения'), ('Файлы', 'Работа с файлами (txt, JSON, CSV)'), ('Алгоритмы', 'Основы алгоритмов (поиск, сортировка)'), ('Мини проект', 'Практика: консольное приложение'), ('ООП', 'Введение в ООП. Классы и объекты'), ('Атрибуты и методы', 'Атрибуты и методы'), ('Наследование', 'Наследование, полиморфизм, инкапсуляция'), ('Магические методы', 'Магические методы'), ('RPG проект', 'Практика: RPG Game'), ('Модули', 'Встроенные и собственные модули'), ('Окружения', 'Виртуальные окружения'), ('Регулярки', 'Регулярные выражения'), ('Финальный проект', 'Итоговый проект месяца')], help_text='Выберите урок, к которому относится задание', max_length=100, verbose_name='Урок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Результат задания',
                'verbose_name_plural': 'Результаты заданий',
            },
        ),
        migrations.CreateModel(
            name='HwItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_condition', models.TextField(verbose_name='Условие задания')),
                ('student_answer', models.TextField(verbose_name='Ответ ученика')),
                ('grade', models.FloatField(blank=True, null=True, verbose_name='Оценка (из 10)')),
                ('ai_feedback', models.TextField(blank=True, null=True, verbose_name='Комментарий от Islam AI Checker')),
                ('originality_check', models.TextField(blank=True, null=True, verbose_name='Анализ оригинальности')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='homework.homework', verbose_name='Домашняя работа')),
            ],
            options={
                'verbose_name': 'Пункт задания',
                'verbose_name_plural': 'Пункты заданий',
            },
        ),
    ]
