# Generated by Django 4.2.24 on 2025-10-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-created_at'], 'verbose_name': 'Результат задания', 'verbose_name_plural': 'Результаты заданий'},
        ),
        migrations.AlterModelOptions(
            name='hwitem',
            options={'ordering': ['id'], 'verbose_name': 'Пункт задания', 'verbose_name_plural': 'Пункты заданий'},
        ),
        migrations.AddField(
            model_name='homework',
            name='student_email',
            field=models.EmailField(default=1, help_text='Введите e-mail ученика', max_length=254, verbose_name='Электронная почта ученика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hwitem',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='Комментарий, сгенерированный системой Islam AI Checker', null=True, verbose_name='Комментарий от Islam AI Checker'),
        ),
        migrations.AlterField(
            model_name='hwitem',
            name='grade',
            field=models.FloatField(blank=True, help_text='Введите оценку за задание (от 0 до 10)', null=True, verbose_name='Оценка (из 10)'),
        ),
        migrations.AlterField(
            model_name='hwitem',
            name='originality_check',
            field=models.TextField(blank=True, help_text='Проверка, сам ли ученик выполнил задание или использовал AI', null=True, verbose_name='Анализ оригинальности'),
        ),
        migrations.AlterField(
            model_name='hwitem',
            name='student_answer',
            field=models.TextField(help_text='Введите ответ ученика', verbose_name='Ответ ученика'),
        ),
        migrations.AlterField(
            model_name='hwitem',
            name='task_condition',
            field=models.TextField(help_text='Введите условие задания, данное ученику', verbose_name='Условие задания'),
        ),
    ]
