services:
  web:
    build:
      context: ./backend
    container_name: todo_web
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: always

  celery_worker:
    build:
      context: ./backend
    container_name: todo_celery
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: always

  celery_beat:
    build:
      context: ./backend
    container_name: todo_celery_beat
    command: celery -A celery_app beat --loglevel=info
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: always

  redis:
    image: redis:7
    container_name: todo_redis
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:15
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
