# Generated by Django 4.2.24 on 2025-09-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Уникальное имя пользователя в Telegram (@username)', max_length=255, unique=True, verbose_name='Юзернейм')),
                ('full_name', models.CharField(help_text='Полное имя пользователя из профиля Telegram', max_length=255, verbose_name='Полное имя')),
                ('telegram_id', models.CharField(help_text='Уникальный идентификатор пользователя в Telegram', max_length=255, verbose_name='Telegram ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Создан')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Когда пользователь впервые начал пользоваться ботом', verbose_name='Дата присоединения')),
            ],
            options={
                'verbose_name': 'Telegram пользователь',
                'verbose_name_plural': 'Telegram пользователи',
                'ordering': ['-created_at'],
            },
        ),
    ]
