# Generated by Django 4.2.24 on 2025-09-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', help_text='Язык интерфейса пользователя', max_length=2, verbose_name='Язык пользователя'),
        ),
    ]
