# Generated by Django 4.2.24 on 2025-10-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='file_name',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
