# Generated by Django 5.1.3 on 2025-09-07 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID исполнителя')),
                ('name', models.CharField(help_text='Введите имя исполнителя (например, Michael Jackson)', max_length=200, unique=True, verbose_name='Имя исполнителя')),
                ('bio', models.TextField(blank=True, help_text='Краткая информация об исполнителе', verbose_name='Биография')),
                ('country', models.CharField(blank=True, help_text='Укажите страну исполнителя', max_length=100, verbose_name='Страна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID альбома')),
                ('title', models.CharField(help_text='Введите название альбома', max_length=255, verbose_name='Название альбома')),
                ('release_year', models.PositiveIntegerField(blank=True, help_text='Укажите год выпуска альбома', null=True, verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, help_text='Краткое описание альбома', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('artist', models.ForeignKey(help_text='Выберите исполнителя альбома', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-release_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID песни')),
                ('title', models.CharField(help_text='Введите название песни', max_length=255, verbose_name='Название песни')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Укажите длительность песни в секундах', null=True, verbose_name='Длительность (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('artist', models.ForeignKey(blank=True, help_text='Исполнитель песни (если отличается от альбома)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='catalog.artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.PositiveIntegerField(help_text='Укажите порядковый номер песни в альбоме', verbose_name='Номер трека')),
                ('album', models.ForeignKey(help_text='Выберите альбом', on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='catalog.album', verbose_name='Альбом')),
                ('song', models.ForeignKey(help_text='Выберите песню', on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='catalog.song', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Трек в альбоме',
                'verbose_name_plural': 'Треки в альбоме',
                'ordering': ['track_number'],
                'unique_together': {('album', 'song'), ('album', 'track_number')},
            },
        ),
    ]
