# Generated by Django 4.2.24 on 2025-10-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название категории (например: Напитки, Десерты, Основные блюда)', max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите изображение товара', upload_to='products/%Y/%m', verbose_name='Фотография товара')),
                ('title', models.CharField(help_text='Введите наименование товара', max_length=100, verbose_name='Название товара')),
                ('description', models.TextField(help_text='Краткое описание товара', verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена товара без скидки', max_digits=10, verbose_name='Цена')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Укажите цену товара со скидкой (если есть)', max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('identification_number', models.CharField(help_text='Введите уникальный код или артикул товара', max_length=100, unique=True, verbose_name='Уникальный ID товара')),
                ('is_archived', models.BooleanField(default=False, help_text='Отметьте, если товар больше не продаётся', verbose_name='В архиве')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Когда товар был добавлен', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Когда товар последний раз редактировался', verbose_name='Дата обновления')),
                ('category', models.ForeignKey(help_text='Выберите категорию, к которой относится товар', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
