# Generated by Django 5.1.3 on 2025-09-06 19:35

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('first_name', models.CharField(blank=True, help_text='Введите имя контакта', max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Введите фамилию контакта (опционально)', max_length=255, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, help_text='Укажите email (необязательно)', max_length=255, null=True, verbose_name='Электронная почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Введите номер телефона в международном формате', max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, help_text='Укажите адрес (необязательно)', null=True, verbose_name='Адрес')),
                ('tags', models.CharField(blank=True, help_text='Укажите теги через запятую, например: друзья, работа, семья', max_length=255, null=True, verbose_name='Теги')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Когда контакт был создан', verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Когда контакт был изменён', verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(help_text='Пользователь, которому принадлежит этот контакт', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец контакта')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['-created_at'],
            },
        ),
    ]
