# Generated by Django 4.2.24 on 2025-10-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_remove_month2homework_file_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='month1homeworkitem',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время проверки'),
        ),
    ]
