# Generated by Django 4.2.24 on 2025-10-13 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=120, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=120, null=True, verbose_name='Имя пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('xp', models.IntegerField(default=0, verbose_name='Опыт (XP)')),
                ('total_read_books', models.IntegerField(default=0, verbose_name='Прочитано книг')),
                ('streak_days', models.IntegerField(default=0, verbose_name='Серия дней подряд')),
                ('last_read_date', models.DateField(blank=True, null=True, verbose_name='Последнее чтение')),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('rank', models.CharField(default='Новичок', help_text='Например: Новичок, Читатель, Мастер чтения', max_length=50, verbose_name='Звание')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
    ]
