# Generated by Django 5.1.3 on 2025-09-05 19:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный UUID для каждой заметки.', primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('title', models.CharField(help_text='Введите заголовок заметки (до 255 символов).', max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите текст заметки.', verbose_name='Содержимое')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда заметка была создана.', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения заметки.', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-created_at'],
            },
        ),
    ]
