version: "3.9"

services:
  bot:
    build: .
    container_name: islamdev_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - .:/app
    command: python main.py

