# Generated by Django 4.2.24 on 2025-10-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=120, unique=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_task_completes', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_task_completed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
