# Generated by Django 4.2.24 on 2025-09-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.CharField(max_length=255, verbose_name='Запрос пользователя (ингредиенты или пожелания)')),
                ('ai_result', models.TextField(blank=True, null=True, verbose_name='Сгенерированный рецепт AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_recipes', to='category.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recipes', to='user.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательский рецепт',
                'verbose_name_plural': 'Пользовательские рецепты',
                'db_table': 'user_recipe',
                'ordering': ['-created_at'],
            },
        ),
    ]
