# Generated by Django 4.2.24 on 2025-10-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название книги', max_length=255, verbose_name='Название книги')),
                ('author', models.CharField(help_text='Введите имя автора книги', max_length=255, verbose_name='Автор')),
                ('total_chapters', models.IntegerField(default=0, help_text='Общее количество глав в книге', verbose_name='Количество глав')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название вашей книги', max_length=255, verbose_name='Название книги')),
                ('description', models.TextField(help_text='Кратко опишите, о чём книга', verbose_name='Описание книги')),
                ('file', models.FileField(help_text='Загрузите файл книги', upload_to='user_books/files/', verbose_name='Файл книги (PDF, TXT и др.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Когда книга была добавлена пользователем', verbose_name='Дата добавления')),
                ('telegram_user', models.ForeignKey(help_text='Пользователь, который добавил книгу', on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to='accounts.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Книга пользователя',
                'verbose_name_plural': 'Книги пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Введите номер главы', verbose_name='Номер главы')),
                ('title', models.CharField(help_text='Введите название главы', max_length=255, verbose_name='Название главы')),
                ('text', models.TextField(help_text='Введите текст главы', verbose_name='Текст главы')),
                ('book', models.ForeignKey(help_text='Выберите книгу, к которой относится эта глава', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='book.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Главы',
                'ordering': ['book', 'number'],
            },
        ),
    ]
