# Generated by Django 4.2.24 on 2025-10-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month3homework',
            name='file_presentation',
        ),
    ]
