# Generated by Django 4.2.24 on 2025-10-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_remove_month3homework_file_presentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month2homework',
            name='file_presentation',
        ),
    ]
