# Generated by Django 4.2.24 on 2025-10-17 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['book', 'number'], 'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text='Введите имя автора книги', max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Введите название книги', max_length=255, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_chapters',
            field=models.IntegerField(default=0, help_text='Общее количество глав в книге', verbose_name='Количество глав'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(help_text='Выберите книгу, к которой относится эта глава', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='book.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(help_text='Введите номер главы', verbose_name='Номер главы'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='text',
            field=models.TextField(help_text='Введите текст главы', verbose_name='Текст главы'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(help_text='Введите название главы', max_length=255, verbose_name='Название главы'),
        ),
    ]
