version: '3.9'

services:
  web:
    build: .
    container_name: django-weasyprint
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    restart: unless-stopped
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120

