version: '3.9'
services:
  web:
    image: python:3.13-slim
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 1
    volumes:
      - .:/code
    working_dir: /code
    expose:
      - "8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media
    depends_on:
      - web
