services:
  web:
    build: .
    container_name: django-web
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    restart: unless-stopped
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120
    depends_on:
      - redis
      - db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    command: python -m celery -A config worker -l info
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    command: python -m celery -A config beat -l info
    depends_on:
      - web
      - redis
