# Generated by Django 4.2.24 on 2025-09-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BroadcastPrompt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastprompt',
            options={'ordering': ['-created_at'], 'verbose_name': 'рассылки', 'verbose_name_plural': 'рассылки'},
        ),
    ]
