# Generated by Django 5.1.3 on 2025-09-13 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание теста')),
            ],
            options={
                'verbose_name': 'Placement Test',
                'verbose_name_plural': 'Placement Tests',
            },
        ),
        migrations.CreateModel(
            name='PlacementTest_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill', 'Fill in the blank'), ('translate', 'Translate'), ('listening', 'Listening')], default='mcq', max_length=20)),
                ('option_a', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант A')),
                ('option_b', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант B')),
                ('option_c', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант C')),
                ('option_d', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант D')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions_images/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='questions_audio/')),
                ('level', models.ForeignKey(blank=True, help_text='К какому уровню относится вопрос (например, A2)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='test.level', verbose_name='Уровень вопроса')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='test.placementtest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
