# Generated by Django 4.2.24 on 2025-10-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='average_score',
            field=models.FloatField(default=0.0, verbose_name='Средний балл'),
        ),
        migrations.AlterField(
            model_name='student',
            name='best_score',
            field=models.FloatField(default=0.0, verbose_name='Лучший балл'),
        ),
        migrations.AlterField(
            model_name='student',
            name='completed_homeworks',
            field=models.PositiveIntegerField(default=0, verbose_name='Выполненные задания'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_homework_done',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее выполненное задание'),
        ),
        migrations.AlterField(
            model_name='student',
            name='progress_level',
            field=models.CharField(default='Новичок', max_length=50, verbose_name='Уровень прогресса'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.PositiveIntegerField(default=0, verbose_name='Рейтинг в группе'),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_homeworks',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего домашних заданий'),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_points',
            field=models.FloatField(default=0.0, verbose_name='Общее количество баллов'),
        ),
    ]
